import React from "react";

<<<<<<< HEAD
export default function Home() {
  return (
    <>
      <Head>
        <title>Bit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Typography variant="h1">Home Page</Typography>
    
      </Box>
    </>
  
  );
}

  
  


=======
const Home = () => {
  return <div><h1>homePage</h1></div>;
};

export default Home;
>>>>>>> e9c7b41ed51d831b1d5b3dd00edf61c09316793d
